version: '3.9'
services:
  api:
    build: .
    container_name: budget-tracker-api
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: budget-tracker-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

